// vue-image-search/src/App.vue
<template>
  <div id="app">
    <h1>{{title}}</h1>
    <form @submit.prevent="formSubmitted()">
        <label for="searchTerm">Search Term</label>
        <input v-model="searchTerm" class="u-full-width" type="text" name="searchTerm" id="searchTerm">
        <button type="submit">Search</button>
    </form>
    <img v-if="loading" src="./loading.gif" alt="loading gif">
    <section class="images">
      <img v-for="image in images" :key="image.id" :src="image.urls.small" :alt="image.description">
    </section>
  </div>
</template>

<script> 

import API from './API';

export default {
  name: 'app',
  data(){
    return{
      title: 'ⓋVue image searchⓋ',
      searchTerm:'',
      images:[],
      loading:false,
    };
  },
  methods:{
    formSubmitted(){
      this.images=[];
      this.loading=true;
      console.log(this.searchTerm)
      API.search(this.searchTerm)
        .then(images => {
          console.log(images);
          this.images=images;
          this.loading=false;
          images.forEach(image =>{
            console.log(image.urls.small)
          })
        })
    }
  }
};
</script>

<style>
  body{
      width: 80%;
      margin: 2em auto 0 auto;
  }
  img{
    width: 100%;
  }
  .images{
    column-count: 3;
  }
</style>

// react-image-search/src/App.js
import React, { Component } from 'react';
import API from './API'
import loadingImage from './loading.gif'

class App extends Component {
  constructor(){
    super();
    this.state={
      title: '⚛️ REACT image search ⚛️ ',
      searchTerm : '',
      loading: false,
      images:[]
      
    };
  }

  searchTermChanged(event){
    console.log(event.target.value);
    this.setState({
      searchTerm: event.target.value
    })
    
  }

  formSubmitted(event){
    event.preventDefault();

    this.setState({
      loading:true,
      images:[]
    })

    API
      .search(this.state.searchTerm)
      .then(images => {
        this.setState({
          images,
          loading:false

        })
      })
    
      //this.setState({
      //  loading:false
      //})
  }

  render() {
    const {title,searchTerm, loading, images} = this.state;  //destructuring
    return (
      <div className="App">
        <h1>{title}</h1>
        <form onSubmit={(event) => this.formSubmitted(event)}>
          <label htmlFor="searchTerm">Search Term</label>
          <input 
            onChange={(event) =>this.searchTermChanged(event)} 
            value ={searchTerm} 
            className="u-full-width" 
            type="text" 
            name="searchTerm" 
            id="searchTerm">
          </input>
          <button type="submit">Search</button>
        </form>
        {loading ? <img className='loading' src={loadingImage} alt=''/> : ''}
        <section className="images">
            {images.map(image => {
              return <img key={image.id} alt={image.description} src={image.urls.small} />
            })}
        </section>
      </div>
        );
      }
    }
    
    export default App;
